# Production configuration for Kleinanzeigen Crawler
# This configuration is optimized for production use

# Search parameters
search:
  category: "antike-buecher"
  location: "Karlsruhe"
  radius_km: 20
  max_price: 0  # Free items only
  keywords:
    - "sammlung"
    - "konvolut"
    - "nachlass"
    - "bücher"
    - "bibliothek"
  
# Selenium settings - optimized for headless production
selenium:
  browser: "chrome"
  headless: true
  window_size: "1920,1080"
  page_load_timeout: 45
  implicit_wait: 15
  user_agent: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36"

# Crawler settings - conservative for production
crawler:
  max_pages: 50
  delay_between_requests: 5  # Higher delay for production
  retry_attempts: 3
  retry_delay: 10
  
# Database settings
database:
  type: "postgresql"
  host: "${DB_HOST}"
  port: 5432
  name: "${DB_NAME}"
  user: "${DB_USER}"
  password: "${DB_PASSWORD}"
  
# Logging settings - production level
logging:
  level: "INFO"
  format: "{time:YYYY-MM-DD HH:mm:ss} | {level} | {name}:{function}:{line} - {message}"
  rotation: "100 MB"
  retention: "30 days"
  
# Notification settings
notifications:
  enabled: true
  email:
    smtp_server: "${SMTP_SERVER}"
    smtp_port: 587
    sender: "${EMAIL_SENDER}"
    password: "${EMAIL_PASSWORD}"
    recipients:
      - "${EMAIL_RECIPIENT}"
  
# Schedule settings - every 6 hours
schedule:
  enabled: true
  cron: "0 */6 * * *"